// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd0fZitZIJs5jZZLdWtNTVbXLrCcfdfPY',
    appId: '1:514970095088:web:dabe1c0ff0e9815af06135',
    messagingSenderId: '514970095088',
    projectId: 'geomania-283d0',
    authDomain: 'geomania-283d0.firebaseapp.com',
    storageBucket: 'geomania-283d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT15gShbPJ1ManDEnXC8qyscAcQTTo8Ys',
    appId: '1:514970095088:android:3935e0cea3ec0032f06135',
    messagingSenderId: '514970095088',
    projectId: 'geomania-283d0',
    storageBucket: 'geomania-283d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5TUivBS1REuQLuKvbVB_5NaetVYf3NQ',
    appId: '1:514970095088:ios:4f3902022d5d043ff06135',
    messagingSenderId: '514970095088',
    projectId: 'geomania-283d0',
    storageBucket: 'geomania-283d0.firebasestorage.app',
    iosBundleId: 'com.northlight.geomania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD5TUivBS1REuQLuKvbVB_5NaetVYf3NQ',
    appId: '1:514970095088:ios:4f3902022d5d043ff06135',
    messagingSenderId: '514970095088',
    projectId: 'geomania-283d0',
    storageBucket: 'geomania-283d0.firebasestorage.app',
    iosBundleId: 'com.northlight.geomania',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd0fZitZIJs5jZZLdWtNTVbXLrCcfdfPY',
    appId: '1:514970095088:web:e69fff6a5734a24ef06135',
    messagingSenderId: '514970095088',
    projectId: 'geomania-283d0',
    authDomain: 'geomania-283d0.firebaseapp.com',
    storageBucket: 'geomania-283d0.firebasestorage.app',
  );
}
